### PR TITLE
#442 - Upgrade to UIMAv3

### PR DESCRIPTION
**Pull request by reckart**
- [x] Pull UIMA and uimaFIT versions up to 3.3.0
- [x] All tests are successful
- [x] Odd problem with `uima.tcas.Annotation` not being in the type system (slot 21 = null) in TimeML module

### CODE REVIEW

**Comment by bethard** [comment]
I'm no longer active in ClearTK development, but I think upgrading ClearTK to UIMAv3 would be excellent. Feel free to go ahead and make any changes necessary.

Do you have the permissions to make a new ClearTK release when complete? If not, let's get them for you. I think dependabot is yelling at us to make an updated release too, so it would be good to merge those changes as well.

**Comment by reckart** [comment]
I have full permissions on this repo/org. 

I do not have sufficient permissions for releases on Sonatype OSS (which I think ClearTK uses as well). 

That said, I also have very little resources at hand. I've posted to the cTAKES list hoping to motivate somebody to join the effort.

**Comment by raghu298** [comment]
It will be an excellent migration to support UIMAV3.
Team is there any estimated timeline when we can enjoy the GA version.

**Comment by reckart** [comment]
Contributions are welcome.

**Comment by reckart** [comment]
I have added a small todo list at the top - in particular currently tests are not successful - not even on the main branch against v2.

**Comment by azazali30** [comment]
@reckart 
I was trying to see the failing tests on your branch , there are tests failing in "clear TK ML CRFsuite" module.
The failure complains below. Looks like de.tudarmstadt.ukp.dkpro.core again depends on lower version of uime-core and uima-fit. 

JCas Class "de.tudarmstadt.ukp.dkpro.core.api.metadata.type.DocumentMetaData", loaded from "jar:file:/home/vagrant/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.metadata-asl/1.10.0/de.tudarmstadt.ukp.dkpro.core.api.metadata-asl-1.10.0.jar!/de/tudarmstadt/ukp/dkpro/core/api/metadata/type/DocumentMetaData.class", is missing required constructor; likely cause is wrong version (UIMA version 3 or later JCas required).
...
...

**Comment by azazali30** [comment]
I dkpro needs and an upgrade to 3.x of uima first.

**Comment by azazali30** [comment]
> I have added a small todo list at the top - in particular currently tests are not successful - not even on the main branch against v2.

i ran the tests on master and it was failing because of svm_learn executables so i dsabled that test and it started passing all other tests. i am not sure how to make svm tests pass. But having said that skipping same tests on your branch did not help it was failing some tests that i have explained in earlier comment

**Comment by reckart** [comment]
DKPro Core 2.2.0 is based on UIMAv3.

**Comment by reckart** [comment]
I have bumped the DKPro Core dependency to 2.2.0 in this branch.

**Comment by reckart** [comment]
@azazali30 could you open a PR with your changes against the branch `refactoring/442-Upgrade-to-UIMAv3`?

**Comment by azazali30** [comment]
@reckart  sure

**Comment by azazali30** [comment]
@reckart  i am getting failure with below exception in clearTK TimeML module 

`Missing UIMA type, JCas Class name: org.apache.uima.jcas.tcas.Annotation, index: 21, jcasRegisteredTypes size: 60
TypeSystem committed?: true
jcasRegisteredTypes:
   0: uima.cas.TOP
   1: uima.cas.AnnotationBase   2: uima.cas.FSArray   3: uima.cas.FloatArray   4: uima.cas.IntegerArray   5: uima.cas.StringArray
   6: uima.cas.BooleanArray   7: uima.cas.ByteArray   8: uima.cas.ShortArray   9: uima.cas.LongArray  10: uima.cas.DoubleArray
  11: uima.cas.EmptyFSList  12: uima.cas.NonEmptyFSList  13: uima.cas.EmptyFloatList  14: uima.cas.NonEmptyFloatList  15: uima.cas.EmptyIntegerList
  16: uima.cas.NonEmptyIntegerList  17: uima.cas.EmptyStringList  18: uima.cas.NonEmptyStringList  19: uima.cas.Sofa  20: uima.tcas.DocumentAnnotation
  21: null  22: org.cleartk.score.type.ScoredAnnotation  23: org.cleartk.token.type.Sentence  24: org.cleartk.token.type.Token  25: org.cleartk.srl.type.Argument
  26: org.cleartk.srl.type.SemanticArgument  27: org.cleartk.srl.type.Chunk  28: org.cleartk.srl.type.Predicate  29: org.cleartk.syntax.constituent.type.TreebankNode  30: org.cleartk.syntax.constituent.type.TerminalTreebankNode
  31: org.cleartk.syntax.constituent.type.TopTreebankNode  32: org.cleartk.syntax.dependency.type.DependencyNode  33: org.cleartk.syntax.dependency.type.TopDependencyNode  34: org.cleartk.timeml.type.Anchor  35: org.cleartk.timeml.type.Event
  36: org.cleartk.timeml.type.Time  37: org.cleartk.timeml.type.DocumentCreationTime  38: org.cleartk.timeml.type.TemporalLink  39: org.cleartk.timeml.type.Text  40: org.cleartk.token.type.Subtoken
  41: org.cleartk.util.type.Parenthetical  42: org.cleartk.ne.type.Ace2005Document  43: org.cleartk.ne.type.Chunk  44: org.cleartk.ne.type.NamedEntityMention  45: org.cleartk.ne.type.GazetteerNamedEntityMention
  46: org.cleartk.test.util.type.AuthorInfo  47: org.cleartk.test.util.type.Chunk  48: org.cleartk.test.util.type.DependencyRelation  49: org.cleartk.test.util.type.Header  50: org.cleartk.test.util.type.Lemma
  51: org.cleartk.test.util.type.NamedEntityMention  52: org.cleartk.test.util.type.Orthography  53: org.cleartk.test.util.type.Parenthetical  54: org.cleartk.test.util.type.PosTag  55: org.cleartk.test.util.type.Sentence
  56: org.cleartk.test.util.type.Token  57: org.cleartk.score.type.ScoredTOP  58: org.cleartk.syntax.dependency.type.DependencyRelation  59: org.cleartk.ne.type.NamedEntity
Dumping all type names
   0: uima.cas.TOP            1: uima.cas.Integer        2: uima.cas.Float          3: uima.cas.String         4: uima.cas.ArrayBase   
   5: uima.cas.FSArray        6: uima.cas.FloatArray     7: uima.cas.IntegerArray    8: uima.cas.StringArray    9: uima.cas.ListBase    
  10: uima.cas.FSList        11: uima.cas.EmptyFSList   12: uima.cas.NonEmptyFSList   13: uima.cas.FloatList     14: uima.cas.EmptyFloatList 
  15: uima.cas.NonEmptyFloatList   16: uima.cas.IntegerList   17: uima.cas.EmptyIntegerList   18: uima.cas.NonEmptyIntegerList   19: uima.cas.StringList  
  20: uima.cas.EmptyStringList   21: uima.cas.NonEmptyStringList   22: uima.cas.Boolean       23: uima.cas.Byte          24: uima.cas.Short       
  25: uima.cas.Long          26: uima.cas.Double        27: uima.cas.BooleanArray   28: uima.cas.ByteArray     29: uima.cas.ShortArray  
  30: uima.cas.LongArray     31: uima.cas.DoubleArray   32: uima.cas.Sofa          33: uima.cas.AnnotationBase   34: uima.tcas.Annotation 
  35: uima.tcas.DocumentAnnotation   36: org.cleartk.score.type.ScoredAnnotation   37: org.cleartk.score.type.ScoredTOP   38: org.cleartk.srl.type.Argument   39: org.cleartk.srl.type.Chunk 
  40: org.cleartk.srl.type.Predicate   41: org.cleartk.srl.type.SemanticArgument   42: org.cleartk.syntax.constituent.type.TreebankNode   43: org.cleartk.syntax.dependency.type.DependencyNode   44: org.cleartk.syntax.dependency.type.DependencyRelation 
  45: org.cleartk.syntax.dependency.type.TopDependencyNode   46: org.cleartk.test.util.type.AuthorInfo   47: org.cleartk.test.util.type.Chunk   48: org.cleartk.test.util.type.DependencyRelation   49: org.cleartk.test.util.type.Header 
  50: org.cleartk.test.util.type.Language   51: org.cleartk.test.util.type.Lemma   52: org.cleartk.test.util.type.NamedEntityMention   53: org.cleartk.test.util.type.Orthography   54: org.cleartk.test.util.type.Parenthetical 
  55: org.cleartk.test.util.type.PosTag   56: org.cleartk.test.util.type.Sentence   57: org.cleartk.test.util.type.Token   58: org.cleartk.timeml.type.Anchor   59: org.cleartk.timeml.type.Event 
  60: org.cleartk.timeml.type.TemporalLink   61: org.cleartk.timeml.type.Text   62: org.cleartk.timeml.type.Time   63: org.cleartk.token.type.Sentence   64: org.cleartk.token.type.Subtoken 
  65: org.cleartk.token.type.Token   66: org.cleartk.type.ne.NamedEntityClass   67: org.cleartk.util.type.Parenthetical   68: org.cleartk.ne.type.Ace2005Document   69: org.cleartk.ne.type.Chunk 
  70: org.cleartk.ne.type.NamedEntity   71: org.cleartk.ne.type.NamedEntityMention   72: org.cleartk.syntax.constituent.type.TerminalTreebankNode   73: org.cleartk.syntax.constituent.type.TopTreebankNode   74: org.cleartk.timeml.type.DocumentCreationTime 
  75: org.cleartk.ne.type.GazetteerNamedEntityMention   76: org.cleartk.srl.type.Argument[]   77: uima.tcas.Annotation[]   78: org.cleartk.syntax.constituent.type.TreebankNode[]   79: org.cleartk.syntax.dependency.type.DependencyRelation[] 
  80: org.cleartk.test.util.type.AuthorInfo[]   81: org.cleartk.test.util.type.PosTag[]   82: org.cleartk.test.util.type.DependencyRelation[]   83: org.cleartk.ne.type.NamedEntityMention[]   84: org.cleartk.syntax.constituent.type.TerminalTreebankNode[] 


org.apache.uima.analysis_engine.AnalysisEngineProcessException: Annotator processing failed.    

	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:415)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:299)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:590)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:422)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:352)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:276)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:295)
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:109)
	at org.cleartk.timeml.TimeMlAnnotate.main(TimeMlAnnotate.java:98)
	at org.cleartk.timeml.TimeMlAnnotateTest.test(TimeMlAnnotateTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.apache.uima.cas.CASRuntimeException: JCas type "org.apache.uima.jcas.tcas.Annotation" used in Java code,  but was not declared in the XML type descriptor.
	at org.apache.uima.cas.impl.TypeSystemImpl.throwMissingUIMAtype(TypeSystemImpl.java:2739)
	at org.apache.uima.cas.impl.TypeSystemImpl.getJCasRegisteredType(TypeSystemImpl.java:2719)
	at org.apache.uima.cas.impl.FeatureStructureImplC.<init>(FeatureStructureImplC.java:232)
	at org.apache.uima.jcas.cas.TOP.<init>(TOP.java:93)
	at org.apache.uima.jcas.cas.AnnotationBase.<init>(AnnotationBase.java:91)
	at org.apache.uima.jcas.tcas.Annotation.<init>(Annotation.java:174)
	at org.cleartk.ml.feature.extractor.CleartkExtractor.extractBetween(CleartkExtractor.java:117)
	at org.cleartk.ml.feature.extractor.CleartkExtractor.extract(CleartkExtractor.java:124)
	at org.cleartk.timeml.tlink.TemporalLinkAnnotator_ImplBase.process(TemporalLinkAnnotator_ImplBase.java:197)
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:50)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.lambda$callProcessMethod$3(AnalysisEngineImplBase.java:669)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.withContexts(AnalysisEngineImplBase.java:698)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.callProcessMethod(AnalysisEngineImplBase.java:668)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:387)
	... 37 more



Disconnected from the target VM, address: '127.0.0.1:41649', transport: 'socket'

Process finished with exit code 255
`
Any clue

**Comment by reckart** [comment]
Not really - another user reported this issue with as well when upgrading a scenario from UIMAv2 to UIMAv3 but so far has not been able to provide a reproducible sharable scenario. If we can reproduce this consistently using open source ClearTK, I can have investigate it. It may take some days before I am able to get to this though.

**Comment by reckart** [comment]
If you have any changes so far, it would be great if you could provide in a PR them so I start off on the latest status. Meanwhile, feel free check the other modules.

**Comment by azazali30** [comment]
sure lemme create a pr

**Comment by azazali30** [comment]
added a pr to your branch

**Comment by azazali30** [comment]
> @reckart i am getting failure with below exception in clearTK TimeML module
> 
> ```
> Missing UIMA type, JCas Class name: org.apache.uima.jcas.tcas.Annotation, index: 21, jcasRegisteredTypes size: 60
> TypeSystem committed?: true
> jcasRegisteredTypes:
>    0: uima.cas.TOP
>    1: uima.cas.AnnotationBase   2: uima.cas.FSArray   3: uima.cas.FloatArray   4: uima.cas.IntegerArray   5: uima.cas.StringArray
>    6: uima.cas.BooleanArray   7: uima.cas.ByteArray   8: uima.cas.ShortArray   9: uima.cas.LongArray  10: uima.cas.DoubleArray
>   11: uima.cas.EmptyFSList  12: uima.cas.NonEmptyFSList  13: uima.cas.EmptyFloatList  14: uima.cas.NonEmptyFloatList  15: uima.cas.EmptyIntegerList
>   16: uima.cas.NonEmptyIntegerList  17: uima.cas.EmptyStringList  18: uima.cas.NonEmptyStringList  19: uima.cas.Sofa  20: uima.tcas.DocumentAnnotation
>   21: null  22: org.cleartk.score.type.ScoredAnnotation  23: org.cleartk.token.type.Sentence  24: org.cleartk.token.type.Token  25: org.cleartk.srl.type.Argument
>   26: org.cleartk.srl.type.SemanticArgument  27: org.cleartk.srl.type.Chunk  28: org.cleartk.srl.type.Predicate  29: org.cleartk.syntax.constituent.type.TreebankNode  30: org.cleartk.syntax.constituent.type.TerminalTreebankNode
>   31: org.cleartk.syntax.constituent.type.TopTreebankNode  32: org.cleartk.syntax.dependency.type.DependencyNode  33: org.cleartk.syntax.dependency.type.TopDependencyNode  34: org.cleartk.timeml.type.Anchor  35: org.cleartk.timeml.type.Event
>   36: org.cleartk.timeml.type.Time  37: org.cleartk.timeml.type.DocumentCreationTime  38: org.cleartk.timeml.type.TemporalLink  39: org.cleartk.timeml.type.Text  40: org.cleartk.token.type.Subtoken
>   41: org.cleartk.util.type.Parenthetical  42: org.cleartk.ne.type.Ace2005Document  43: org.cleartk.ne.type.Chunk  44: org.cleartk.ne.type.NamedEntityMention  45: org.cleartk.ne.type.GazetteerNamedEntityMention
>   46: org.cleartk.test.util.type.AuthorInfo  47: org.cleartk.test.util.type.Chunk  48: org.cleartk.test.util.type.DependencyRelation  49: org.cleartk.test.util.type.Header  50: org.cleartk.test.util.type.Lemma
>   51: org.cleartk.test.util.type.NamedEntityMention  52: org.cleartk.test.util.type.Orthography  53: org.cleartk.test.util.type.Parenthetical  54: org.cleartk.test.util.type.PosTag  55: org.cleartk.test.util.type.Sentence
>   56: org.cleartk.test.util.type.Token  57: org.cleartk.score.type.ScoredTOP  58: org.cleartk.syntax.dependency.type.DependencyRelation  59: org.cleartk.ne.type.NamedEntity
> Dumping all type names
>    0: uima.cas.TOP            1: uima.cas.Integer        2: uima.cas.Float          3: uima.cas.String         4: uima.cas.ArrayBase   
>    5: uima.cas.FSArray        6: uima.cas.FloatArray     7: uima.cas.IntegerArray    8: uima.cas.StringArray    9: uima.cas.ListBase    
>   10: uima.cas.FSList        11: uima.cas.EmptyFSList   12: uima.cas.NonEmptyFSList   13: uima.cas.FloatList     14: uima.cas.EmptyFloatList 
>   15: uima.cas.NonEmptyFloatList   16: uima.cas.IntegerList   17: uima.cas.EmptyIntegerList   18: uima.cas.NonEmptyIntegerList   19: uima.cas.StringList  
>   20: uima.cas.EmptyStringList   21: uima.cas.NonEmptyStringList   22: uima.cas.Boolean       23: uima.cas.Byte          24: uima.cas.Short       
>   25: uima.cas.Long          26: uima.cas.Double        27: uima.cas.BooleanArray   28: uima.cas.ByteArray     29: uima.cas.ShortArray  
>   30: uima.cas.LongArray     31: uima.cas.DoubleArray   32: uima.cas.Sofa          33: uima.cas.AnnotationBase   34: uima.tcas.Annotation 
>   35: uima.tcas.DocumentAnnotation   36: org.cleartk.score.type.ScoredAnnotation   37: org.cleartk.score.type.ScoredTOP   38: org.cleartk.srl.type.Argument   39: org.cleartk.srl.type.Chunk 
>   40: org.cleartk.srl.type.Predicate   41: org.cleartk.srl.type.SemanticArgument   42: org.cleartk.syntax.constituent.type.TreebankNode   43: org.cleartk.syntax.dependency.type.DependencyNode   44: org.cleartk.syntax.dependency.type.DependencyRelation 
>   45: org.cleartk.syntax.dependency.type.TopDependencyNode   46: org.cleartk.test.util.type.AuthorInfo   47: org.cleartk.test.util.type.Chunk   48: org.cleartk.test.util.type.DependencyRelation   49: org.cleartk.test.util.type.Header 
>   50: org.cleartk.test.util.type.Language   51: org.cleartk.test.util.type.Lemma   52: org.cleartk.test.util.type.NamedEntityMention   53: org.cleartk.test.util.type.Orthography   54: org.cleartk.test.util.type.Parenthetical 
>   55: org.cleartk.test.util.type.PosTag   56: org.cleartk.test.util.type.Sentence   57: org.cleartk.test.util.type.Token   58: org.cleartk.timeml.type.Anchor   59: org.cleartk.timeml.type.Event 
>   60: org.cleartk.timeml.type.TemporalLink   61: org.cleartk.timeml.type.Text   62: org.cleartk.timeml.type.Time   63: org.cleartk.token.type.Sentence   64: org.cleartk.token.type.Subtoken 
>   65: org.cleartk.token.type.Token   66: org.cleartk.type.ne.NamedEntityClass   67: org.cleartk.util.type.Parenthetical   68: org.cleartk.ne.type.Ace2005Document   69: org.cleartk.ne.type.Chunk 
>   70: org.cleartk.ne.type.NamedEntity   71: org.cleartk.ne.type.NamedEntityMention   72: org.cleartk.syntax.constituent.type.TerminalTreebankNode   73: org.cleartk.syntax.constituent.type.TopTreebankNode   74: org.cleartk.timeml.type.DocumentCreationTime 
>   75: org.cleartk.ne.type.GazetteerNamedEntityMention   76: org.cleartk.srl.type.Argument[]   77: uima.tcas.Annotation[]   78: org.cleartk.syntax.constituent.type.TreebankNode[]   79: org.cleartk.syntax.dependency.type.DependencyRelation[] 
>   80: org.cleartk.test.util.type.AuthorInfo[]   81: org.cleartk.test.util.type.PosTag[]   82: org.cleartk.test.util.type.DependencyRelation[]   83: org.cleartk.ne.type.NamedEntityMention[]   84: org.cleartk.syntax.constituent.type.TerminalTreebankNode[] 
> 
> 
> org.apache.uima.analysis_engine.AnalysisEngineProcessException: Annotator processing failed.    
> 
> 	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:415)
> 	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:299)
> 	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:590)
> 	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:422)
> 	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:352)
> 	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:276)
> 	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:295)
> 	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:109)
> 	at org.cleartk.timeml.TimeMlAnnotate.main(TimeMlAnnotate.java:98)
> 	at org.cleartk.timeml.TimeMlAnnotateTest.test(TimeMlAnnotateTest.java:70)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
> 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
> 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
> 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
> 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
> 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
> 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
> 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
> 	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
> 	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
> 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
> Caused by: org.apache.uima.cas.CASRuntimeException: JCas type "org.apache.uima.jcas.tcas.Annotation" used in Java code,  but was not declared in the XML type descriptor.
> 	at org.apache.uima.cas.impl.TypeSystemImpl.throwMissingUIMAtype(TypeSystemImpl.java:2739)
> 	at org.apache.uima.cas.impl.TypeSystemImpl.getJCasRegisteredType(TypeSystemImpl.java:2719)
> 	at org.apache.uima.cas.impl.FeatureStructureImplC.<init>(FeatureStructureImplC.java:232)
> 	at org.apache.uima.jcas.cas.TOP.<init>(TOP.java:93)
> 	at org.apache.uima.jcas.cas.AnnotationBase.<init>(AnnotationBase.java:91)
> 	at org.apache.uima.jcas.tcas.Annotation.<init>(Annotation.java:174)
> 	at org.cleartk.ml.feature.extractor.CleartkExtractor.extractBetween(CleartkExtractor.java:117)
> 	at org.cleartk.ml.feature.extractor.CleartkExtractor.extract(CleartkExtractor.java:124)
> 	at org.cleartk.timeml.tlink.TemporalLinkAnnotator_ImplBase.process(TemporalLinkAnnotator_ImplBase.java:197)
> 	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:50)
> 	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.lambda$callProcessMethod$3(AnalysisEngineImplBase.java:669)
> 	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.withContexts(AnalysisEngineImplBase.java:698)
> 	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.callProcessMethod(AnalysisEngineImplBase.java:668)
> 	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:387)
> 	... 37 more
> 
> 
> 
> Disconnected from the target VM, address: '127.0.0.1:41649', transport: 'socket'
> 
> Process finished with exit code 255
> ```
> 
> Any clue

@reckart if i skit these two modules all the tests are passing with my changes merged in your branch
if you get time can you please look into the above issue and not sure why svm light is failing in master as well as your branch it requires svm_learn i installed but still it fails.

I am able to run tests successfully if i skip these two modules which has tests failing

`mvn clean test -Dcleartk.skipTests=svmlight,bigMem `

**Comment by reckart** [comment]
The error is a pretty pathological one - I'm trying to implement a workaround in UIMA: https://github.com/apache/uima-uimaj/pull/243

**Comment by reckart** [comment]
@azazali30 I have pushed a workaround for the https://github.com/apache/uima-uimaj/issues/234 issue to this branch. However, the timeml tests still do not complete successfully on my machine because the order of annotations in the TimeML output changes compared to v2 (the content is the same, but the order is different) - and the test case is not robust against this change. Could you look into that maybe?

**Comment by reckart** [comment]
@azazali30 I have switched to tests in cleartk-ml to use assertj to get better failure messages. Looks like for some reason the manifest that ClearTK generates there is in the GitHub build different from what ClearTK expects. Locally, it works for me... it seems to be a question of which Java version is used to build. With Java 8 it seems to work as ClearTK expects, with Java 11 the test also fails locally for me.

**Comment by reckart** [comment]
Switched to build to using Java 8... now we have this:

```
java.io.IOException: Cannot run program "svm_learn": error=2, No such file or directory
```

@azazali30 could you look into that maybe?

**Comment by azazali30** [comment]
> Switched to build to using Java 8... now we have this:
> 
> ```
> java.io.IOException: Cannot run program "svm_learn": error=2, No such file or directory
> ```
> 
> @azazali30 could you look into that maybe?

Not sure how it was working before the error seems to be -
Java is not executing svm_learn command through current logged in user if i  use
String[] command = new String[] { "bash", "-l", "-c", "svm_learn"};  
it works and tests are passing 
Maybe @bethard  can you please suggest it was working before and if we are doing some thing wrong while installing svm_light . Thanks

**Pull request merged**
